[
  {
    DateObserved: "2024-06-21",
    HourObserved: 6,
    LocalTimeZone: "EST",
    ReportingArea: "Northern Virginia/DC",
    StateCode: "DC",
    Latitude: 38.919,
    Longitude: -77.013,
    ParameterName: "O3",
    AQI: 25,
    Category: { Number: 1, Name: "Good" },
  },
  {
    DateObserved: "2024-06-21",
    HourObserved: 6,
    LocalTimeZone: "EST",
    ReportingArea: "Northern Virginia/DC",
    StateCode: "DC",
    Latitude: 38.919,
    Longitude: -77.013,
    ParameterName: "PM2.5",
    AQI: 46,
    Category: { Number: 1, Name: "Good" },
  },
  {
    DateObserved: "2024-06-21",
    HourObserved: 6,
    LocalTimeZone: "EST",
    ReportingArea: "Northern Virginia/DC",
    StateCode: "DC",
    Latitude: 38.919,
    Longitude: -77.013,
    ParameterName: "PM10",
    AQI: 14,
    Category: { Number: 1, Name: "Good" },
  },
];
